{"text": "\u201e\u00abTodo es amor\u2026 todo es amor. Con el amor llega la comprensi\u00f3n. Con la comprensi\u00f3n llega la paciencia. Y entonces el tiempo se detiene. Y todo es ahora.\u00bb\u201c", "autor": "Brian L. Weiss", "tags": ["De amor", "Comprensi\u00f3n", "Paciencia"]}
{"text": "\u201eEl Arte es un hijo al cual ves nacer y crecer, d\u00e1ndole todo tu amor y atenci\u00f3n hasta los \u00faltimos d\u00edas de tu vida.\u201c", "autor": "Jhoan Roa", "tags": ["De amor", "De vida", "De arte"]}
{"text": "\u201ePorque usted sabe, general, que mover un pa\u00eds, por peque\u00f1o que sea, es obra de gigantes. Y quien no se sienta gigante de amor, o de valor, o de pensamiento, o de paciencia, no debe emprenderla\u201c", "autor": "Jos\u00e9 Mart\u00ed", "tags": ["De amor", "Pa\u00eds", "Valor", "Paciencia"]}
{"text": "\u201eEs cierto, no hay planes celestiales ni infernales. Pero cuando uno est\u00e1 enamorado busca explicar el rechazo en t\u00e9rminos de intriga. El amor es fatal para el pensamiento. La gente empieza a creer en gualichos, en maldiciones, en conexiones m\u00e1gicas. Siga un consejo: no se enamore.\u201c", "autor": "Alejandro Dolina", "tags": ["De amor", "De gente"]}
{"text": "\u201eSi Eva hubiera escrito el G\u00e9nesis, \u00bfc\u00f3mo ser\u00eda la primera noche de amor del g\u00e9nero humano? Eva hubiera empezado por aclarar que ella no naci\u00f3 de ninguna costilla, ni conoci\u00f3 a ninguna serpiente, ni ofreci\u00f3 manzanas a nadie, y que Dios nunca le dijo que parir\u00e1s con dolor y tu marido te dominar\u00e1. Que todas esas historias son puras mentiras que Ad\u00e1n cont\u00f3 a la prensa.\u201c", "autor": "Eduardo Galeano", "tags": ["De amor", "De Dios", "De dolor", "De mentira"]}
{"text": "\u201eEst\u00e1s ciego al creer que podr\u00e1s evitar este jard\u00edn de gente. Con dinero no se inventa el amor.\u201c", "autor": "Luis Alberto Spinetta", "tags": ["De amor", "De dinero", "De gente"]}
{"text": "\u201eEl nacionalismo de ustedes se parece al amor del hijo junto a la tumba del padre; el nuestro, se parece al amor del padre junto a la cuna del hijo. [\u2026] Para ustedes la Naci\u00f3n se realiz\u00f3 y fue derogada; para nosotros, todav\u00eda sigue naciendo.\u201c", "autor": "Arturo Jauretche", "tags": ["De amor", "Padre"]}
{"text": "\u201eSi puedes elegir busca un minuto de gloria con amor. Que una vida vivida sin amor\u201c", "autor": "emilispain", "tags": ["De amor", "De vida"]}
{"text": "\u201eEl agua apaga el fuego", "autor": "Joaqu\u00edn Sabina", "tags": ["De amor", "Agua"]}
{"text": "\u201eEl amor es invisible y entra y sale por donde quiere sin que nadie le pida cuenta de sus hechos.\u201c", "autor": "Miguel de Cervantes", "tags": ["De amor"]}
{"text": "\u201eCalla, calla, princesa \u2014dice el hada madrina\u2014;", "autor": "Rub\u00e9n Dar\u00edo", "tags": ["De amor", "De muerte", "Caballo", "Beso"]}
{"text": "\u201eAnhelaba volver a la inconsciencia de entonces, a sentir tanto amor sin saberlo y a confundirlo con las risas.\u201c", "autor": "Markus Zusak", "tags": ["De amor"]}
{"text": "\u201eSaukerl, musit\u00f3 Liesel riendo y, cuando levant\u00f3 la mano, supo sin lugar a", "autor": "Markus Zusak", "tags": ["De amor"]}
{"text": "\u201eEl agua apaga al fuego y al ardor los a\u00f1os. Amor se llama el juego en el que un par de ciegos juegan a hacerse da\u00f1o.\u201c", "autor": "Joaqu\u00edn Sabina", "tags": ["De amor", "Agua"]}
{"text": "\u201eNada es jam\u00e1s libre si no viene de la voluntad; o lo que es lo mismo, de la inclinaci\u00f3n que es del amor, porque todo cuanto el hombre quiere o ama esto hace con libertad\u201c", "autor": "Emanuel Swedenborg", "tags": ["De amor", "De hombres", "De libros", "Libertad"]}
{"text": "\u201eLas Iglesias dicen que la expresi\u00f3n del amor en una relaci\u00f3n heterosexual mon\u00f3gama incluye lo f\u00edsico, las caricias, abrazarse, besarse, el acto genital. La totalidad de nuestro amor nos hace crecer en lo divino y en lo compasivo. Si esto es as\u00ed para los heterosexules, \u00bfqu\u00e9 raz\u00f3n terrenal tenemos para decir que no es el caso de los homosexuales?\u201c", "autor": "Desmond Tutu", "tags": ["De amor"]}
{"text": "\u201eLo opuesto al amor no es el odio sino la apat\u00eda.\u201c", "autor": "Rollo May", "tags": ["De amor", "De odio"]}
{"text": "\u201eDir\u00edase que el amor se ha prostituido, al pasar por el coraz\u00f3n de tantos imb\u00e9ciles\".\u201c", "autor": "Andr\u00e9 Gide", "tags": ["De amor", "Coraz\u00f3n"]}
{"text": "\u201eAPRENDIENDO", "autor": "Jorge Luis Borges", "tags": ["De amor", "De vida", "De amistad", "De felicidad/suerte"]}
{"text": "\u201ePuedo escribir los versos m\u00e1s tristes esta noche.", "autor": "Pablo Neruda", "tags": ["De amor", "De dolor", "Noche", "Coraz\u00f3n"]}
{"text": "\u201eS\u00f3lo el santo santifica; s\u00f3lo la luz alumbra; s\u00f3lo el amor calienta.\u201c", "autor": "Alberto Hurtado", "tags": ["De amor"]}
{"text": "\u201eAmar significaba tiranizar y dominar\u2026 El amor es una lucha que empieza con odio y termina con el sometimiento del objeto amado.\u201c", "autor": "Fi\u00f3dor Dostoyevski", "tags": ["De amor", "De odio", "Lucha"]}
{"text": "\u201eSabr\u00e1s que no te amo y que te amo", "autor": "Pablo Neruda", "tags": ["De amor", "De vida", "De destino", "Silencio"]}
{"text": "\u201eEs tan dif\u00edcil encontrar quien te asegure o te jure; Un amor que para siempre dure.\u201c", "autor": "Arc\u00e1ngel (cantante)", "tags": ["De amor"]}
{"text": "\u201eCuando se quiere, no hay excusas. El amor que pudo morir, no era amor.!!! acu\u00e9rdense de eso!.\u201c", "autor": "Arc\u00e1ngel (cantante)", "tags": ["De amor"]}
{"text": "\u201e\u00ab\u00bfPor qu\u00e9 el diminutivo es se\u00f1al de cari\u00f1o? \u2014iba dici\u00e9ndose Augusto camino de su casa\u2014. \u00bfEs acaso que el amor achica la cosa amada?\u201c", "autor": "Miguel de Unamuno", "tags": ["De amor", "Camino"]}
{"text": "\u201eSi s\u00e9 lo que es el amor, es por ti.\u201c", "autor": "Hermann Hesse", "tags": ["De amor"]}
{"text": "\u201eNo hay cosa m\u00e1s dulce que el amor; nada m\u00e1s fuerte, nada m\u00e1s alto, nada m\u00e1s ancho, nada m\u00e1s alegre, nada m\u00e1s lleno, ni mejor en el cielo ni en la tierra; porque el amor naci\u00f3 de Dios, y no puede aquietarse con todo lo criado, sino con el mismo Dios.\u201c", "autor": "Tom\u00e1s de Kempis", "tags": ["De amor", "De Dios", "Fuerte"]}
{"text": "\u201eEntonces descubres que el monstruo del cual hu\u00edas es el monstruo dentro de ti. Mejor aferrarse al amor, el cambio llegar\u00e1.\u201c", "autor": "Darren Hayes", "tags": ["De amor", "De fe", "Cambio"]}
{"text": "\u201eEl amor es un deseo irresistible de ser irresistiblemente deseado.\u201c", "autor": "Robert Lee Frost", "tags": ["De amor"]}
{"text": "\u201eUna relaci\u00f3n de persona a persona (\u2026): el amor que consiste en que dos soledades se defiendan mutuamente, se delimiten y se rindan homenaje.\u201c", "autor": "Rainer Maria Rilke", "tags": ["De amor", "De vejez", "Soledad"]}
{"text": "\u201ePero el poder \u2014como el amor\u2014 es de doble filo: se ejerce y se padece.\u201c", "autor": "Gabriel Garc\u00eda M\u00e1rquez", "tags": ["De amor"]}
{"text": "\u201eUna audiencia es solo un espejo de lo que est\u00e1 sucediendo en el escenario, y si lo que est\u00e1 sucediendo en el escenario tiene amor, sentimiento real y convicci\u00f3n, fuerza y pureza, entonces realmente los estamos reflejando, porque es su propia naturaleza lo que est\u00e1 regresando. Todo es. La musica es. Para m\u00ed, las \u00fanicas barreras en la m\u00fasica son las barreras en el m\u00fasico y en el equipo que tiene que usar. Si un m\u00fasico no tiene barreras dentro de s\u00ed mismo, entonces no hay barreras dentro de su m\u00fasica. Su \u00fanica batalla es con los problemas de expresar su verdadera naturaleza contra las dificultades del mundo real: los l\u00edmites de sus amplificadores y su guitarra o su piano o lo que sea, los l\u00edmites que el mundo exterior impone a la perfecci\u00f3n natural del esp\u00edritu.\u201c", "autor": "John McLaughlin", "tags": ["De amor", "De mundo", "De m\u00fasica", "Problema"]}
{"text": "\u201eConocer es perdonar, dicen. No, perdonar es conocer. Primero el amor, el conocimiento despu\u00e9s.\u201c", "autor": "Miguel de Unamuno", "tags": ["De amor", "Conocimiento"]}
{"text": "\u201eAceptando el compromiso de como hemos sido, de como somos, y de como probablemente seremos\u2026quiz\u00e1s vivamos juntos con un amor inquebrantable y una buena salud, amen.\u201c", "autor": "Jonathan Safran Foer", "tags": ["De amor", "De salud"]}
{"text": "\u201eEntre dos seres existe siempre una distancia singular, infranqueable, un santuario impenetrable. Unas veces adquiere forma de soledad. Otras, de amor\u201c", "autor": "Jonathan Safran Foer", "tags": ["De amor", "Soledad"]}
{"text": "\u201eAmar a distancia es una gran prueba de amor.\u201c", "autor": "Alejandro Sanz", "tags": ["De amor"]}
{"text": "\u201eEl amor combinado con odio es m\u00e1s poderoso que el amor. O que el odio.\u201c", "autor": "Joyce Carol Oates", "tags": ["De amor", "De odio"]}
{"text": "\u201eUno no se mata por el amor de una mujer. Uno se mata porque un amor, cualquier amor, nos revela nuestra desnudez, nuestra miseria, nuestro desamparo, la nada.\u201c", "autor": "Cesare Pavese", "tags": ["De amor", "De mujeres"]}
{"text": "\u201eEl amor de un ser humano por otro, es posiblemente la prueba m\u00e1s dif\u00edcil para cada uno de nosotros.\u201c", "autor": "Rainer Maria Rilke", "tags": ["De amor"]}
{"text": "\u201eAma y haz lo que quieras. Si callas, callar\u00e1s con amor; si gritas, gritar\u00e1s con amor; si corriges, corregir\u00e1s con amor; si perdonas, perdonar\u00e1s con amor. Si tienes el amor arraigado en ti, ninguna otra cosa sino amor ser\u00e1n tus frutos.\u201c", "autor": "Agust\u00edn de Hipona", "tags": ["De amor", "Perd\u00f3n"]}
{"text": "\u201ePrimero el amor, el conocimiento despu\u00e9s.\u201c", "autor": "Miguel de Unamuno", "tags": ["De amor", "Conocimiento"]}
{"text": "\u201eQuien, por un amor demasiado grande, lo que al fin y al cabo es monstruoso, muere de sufrimiento, renace para no conocer ni amor ni odio, sino para disfrutar. Y ese disfrute de la vida, por haberse adquirido de forma no natural, es un veneno que tarde temprano corrompe al mundo entero. Lo que nace m\u00e1s all\u00e1 de los l\u00edmites del sufrimiento humano act\u00faa como un boomerang y provoca destrucci\u00f3n.\u201c", "autor": "Henry Miller", "tags": ["De amor", "De vida", "De odio", "De mundo"]}
{"text": "\u201eSin amor el paso del tiempo nos convierte en unos miserables. Incapaces de reconocerlo\u201c", "autor": "emilispain", "tags": ["De amor"]}
{"text": "\u201eQuien ama verdaderamente no puede amar lo contrario y lo opuesto de aquello que ama, y \u00e9sta es la raz\u00f3n por la cual aquellos que fueron, en un determinado momento de la vida, los m\u00e1s grandes enemigos de Cristo, convi\u00e9rtense, tocados por la Gracia Divina, en sus m\u00e1s ardientes y fogosos defensores. El Amor y el odio est\u00e1n estrechamente unidos entre s\u00ed y quien quiera suprimir la c\u00f3lera suprima al mismo tiempo la caridad. Quienes son incapaces de enardecerse por la ira tambi\u00e9n lo ser\u00e1n respecto del amor: son los eternos tibios que la boca de Dios, conforme est\u00e1 escrito en el Apocalipsis, vomitar\u00e1.\u201c", "autor": "Giovanni Papini", "tags": ["De amor", "De vida", "De odio", "De verdad"]}
{"text": "\u201eCuando un pueblo est\u00e1 decidido a ser esclavo y se halla degradado, es una locura tratar de animar de nuevo en \u00e9l el esp\u00edritu de orgullo y honor, de libertad y amor a las leyes, pues abraza con entusiasmo sus cadenas con tal que lo alimenten sin ning\u00fan esfuerzo por su parte.\u201c", "autor": "Cicer\u00f3n", "tags": ["De amor", "De leyes", "Esfuerzo", "Libertad"]}
{"text": "\u201eEs bueno amar tanto como se pueda, porque ah\u00ed radica la verdadera fuerza, y el que mucho ama realiza grandes cosas y se siente capaz, y lo que se hace por amor est\u00e1 bien hecho.\u201c", "autor": "Vincent Van Gogh", "tags": ["De amor", "De verdad", "De paz"]}
{"text": "\u201e\u00a1Quiero amor y todas las atenciones que sabes darme, y quiero indiferencia si solo quieres herirme!\u201c", "autor": "Tiziano Ferro", "tags": ["De amor", "De fe", "Indiferencia"]}
{"text": "\u201eNo quiero nadie a mil alrededor que me salpique esta condena que algunos todav\u00eda llaman amor.\u201c", "autor": "Ram\u00f3n Melendi", "tags": ["De amor"]}
{"text": "\u201eY quisiera ver en ti la luz, que encontre alg\u00fan d\u00eda pero no eras tu, fue tan solo un simple reflejo de la condicion de mi coraz\u00f3n, que tiende a sufrir cuando habla de amor.\u201c", "autor": "Ram\u00f3n Melendi", "tags": ["De amor", "Coraz\u00f3n"]}
{"text": "\u201eEl amor no es s\u00f3lo un sentimiento; es una fuerza, una que, en el fondo, es m\u00e1s poderosa que cualquier tipo de violencia.\u201c", "autor": "Marianne Williamson", "tags": ["De amor"]}
{"text": "\u201eMAPA ANTIGUO. En un amor, la mayor\u00eda busca una patria eterna. Otros, aunque muy pocos, un eterno viajar. Estos \u00faltimos son melanc\u00f3licos que tienen que rehuir el contacto con la madre tierra. Buscan a quien mantenga alejada de ellos la melancol\u00eda de la patria. Y le guardan fidelidad. Los tratados medievales sobre los humores saben de la apetencia de viajes largos de este tipo de gente.\u201c", "autor": "Walter Benjamin", "tags": ["De amor", "De gente", "Viajar"]}
{"text": "\u201eNo es la fuerza de gravedad lo que mantiene el universo en equilibrio, sino la fuerza adhesiva del amor.\u201c", "autor": "Isabel Allende", "tags": ["De amor", "Universo"]}
{"text": "\u201eEl amor es un misterio, una obsesi\u00f3n; un tema inevitable desde todos sus aspectos posibles, como la memoria y el exilio.\u201c", "autor": "Juan Gelman", "tags": ["De amor", "Memoria"]}
{"text": "\u201eLo que mucha gente llama amar consiste en elegir a una mujer y casarse con ella. La eligen, te lo juro, los he visto. Como si se pudiese elegir en el amor, como si no fuera un rayo que te parte los huesos y te deja estaqueado en la mitad del patio. Vos dir\u00e1s que la eligen porque-la-aman, yo creo que es al rev\u00e9s. A Beatriz no se la elige, a Julieta no se la elige. Vos no eleg\u00eds la lluvia que te va a calar hasta los huesos cuando sal\u00eds de un concierto\"\u201c", "autor": "Julio Cort\u00e1zar", "tags": ["De amor", "De mujeres", "De gente", "De arte"]}
{"text": "\u201eEl amor es demasiado joven para apreciar lo que es conciencia, y, sin embargo, todos saben que la conciencia es engendro del amor.\u201c", "autor": "William Shakespeare", "tags": ["De amor"]}
{"text": "\u201eRe\u00edrse con otro es el mayor s\u00edntoma de amor.\u201c", "autor": "Carmen Mart\u00edn Gaite", "tags": ["De amor"]}
{"text": "\u201eAh, \u00bfesperabas que jugara limpio? Soy el dios del amor. Nunca soy justo.\u201c", "autor": "Rick Riordan", "tags": ["De amor", "De Dios"]}
{"text": "\u201eCuando los alumnos ven amor de padre en el maestro e inter\u00e9s de su aprovechamiento, van con gusto a la escuela, aunque no haya representaciones.\u201c", "autor": "San Jos\u00e9 de Calasanz", "tags": ["De amor", "De escuela", "Padre", "Maestros"]}
{"text": "\u201eNo s\u00e9, todav\u00eda qu\u00e9 es lo que separa el aprecio del amor.\u201c", "autor": "Jane Austen", "tags": ["De amor"]}
{"text": "\u201eSoy una tremenda pecadora, porque fui una buscadora de amor. No me daba cuenta de que el amor no se busca, se encuentra.\u201c", "autor": "Tita Merello", "tags": ["De amor"]}
{"text": "\u201eAhora s\u00e9 por qu\u00e9 los jud\u00edos y los musulmanes tienen novecientos nombres para denominar a Dios; al amor no le basta con una palabra.\u201c", "autor": "Diana Gabaldon", "tags": ["De amor", "De Dios"]}
{"text": "\u201eLo que el hombre necesita en la vida es amor, amar y ser amado. La felicidad no es posible sin el amor. Amar a otra persona es querer su libertad, que se acerque lo m\u00e1s posible a ella, es decir, al bien. Esa es su gran meta. Ayudar\u201c", "autor": "Enrique Rojas", "tags": ["De amor", "De vida", "De hombres", "De felicidad/suerte"]}
{"text": "\u201eEl amor f\u00edsico no es la felicidad del hombre. Si eso fuera as\u00ed, las personas m\u00e1s felices del mundo ser\u00edan las prostitutas.\u201c", "autor": "Jorge Loring", "tags": ["De amor", "De felicidad/suerte", "De mundo", "De fe"]}
{"text": "\u201eEs una gran cosa amar y ser amado. El amor no es algo que pueda ser desaprovechado.\u201c", "autor": "Cassandra Clare", "tags": ["De amor"]}
{"text": "\u201eEl amor es una cosa y la palabra amor es otra cosa, y s\u00f3lo el alma sabe d\u00f3nde las dos se encuentran.\u201c", "autor": "Juan Gelman", "tags": ["De amor", "Alma"]}
{"text": "\u201eel amor entre mujeres es un refugio y un escape hacia la armon\u00eda. En el amor entre hombre y mujer hay resistencia y conflicto, dos mujeres no se juzgan mutuamente, no se embrutecen mutuamente, no buscan nada que ridiculizar. Se rinden al sentimentalismo, a la comprensi\u00f3n mutua, al romanticismo. Ese amor es la muerte, lo admito.\u201c", "autor": "Ana\u00efs Nin", "tags": ["De amor", "De muerte", "De mujeres", "De hombres"]}
{"text": "\u201eNo existe amor tan verdadero como el que muere sin revelarse\u201c", "autor": "Juan Jos\u00e9 Ben\u00edtez", "tags": ["De amor", "De verdad"]}
{"text": "\u201eEl sexo sin amor es una experiencia vac\u00eda. Pero de todas las experiencias vac\u00edas que existen, hay que reconocer que es una de las mejores.\u201c", "autor": "Woody Allen", "tags": ["De amor", "De sexo"]}
{"text": "\u201eEl dolor es el alimento esencial del amor; cualquier amor que no se haya nutrido de un poco de dolor puro, muere.\u201c", "autor": "Maurice Maeterlinck", "tags": ["De amor", "De dolor"]}
{"text": "\u201ePero las rosas se marchitan y se acabar\u00e1 el verano y las promesas de amor ser\u00e1n rotas. Por eso nunca jures amor, O, si lo haces, recuerda que ninguna promesa dar\u00e1 eternidad a la rosa ni impedir\u00e1 que el sol se ponga, ni traer\u00e1 un segundo verano.\u201c", "autor": "Safo", "tags": ["De amor", "Verano"]}
{"text": "\u201eAs\u00ed como las personas que mueren en su plenitud nos ahorran el recuerdo de su vejez, los amores interrumpidos abruptamente siguen viviendo en nuestro coraz\u00f3n; no como brasas agonizantes, sino como horrorosas llamas que queman cada noche.\u201c", "autor": "Alejandro Dolina", "tags": ["De amor", "De vejez", "Noche", "Coraz\u00f3n"]}
{"text": "\u201eNo buscamos la sociedad por amor a ella misma, sino por los honores o los beneficios que puede reportarnos.\u201c", "autor": "Thomas Hobbes", "tags": ["De amor", "De vejez"]}
{"text": "\u201eSi el amor debe ser inolvidable, las casualidades deben volar hacia \u00e9l desde el primer momento, como los p\u00e1jaros hacia los hombros de San Francisco de As\u00eds.\u201c", "autor": "Milan Kundera", "tags": ["De amor", "De hombres", "P\u00e1jaro"]}
{"text": "\u201eAl igual que la tierra necesita ser regada para dar frutos, el humano necesita amor y esperanza por supervivencia\u201c", "autor": "emilispain", "tags": ["De amor", "De sexo"]}
{"text": "\u201eTambi\u00e9n Dios tiene su infierno: es su amor a los hombres.\u201c", "autor": "Friedrich Nietzsche", "tags": ["De amor", "De hombres", "De Dios", "Infierno"]}
{"text": "\u201eSue\u00f1o de amor de Litz se tocar\u00e1 al principio del mal, despu\u00e9s ser\u00e1 la m\u00fasica negra, luego la electr\u00f3nica y al final de finales, la m\u00fasica Kampi.\u201c", "autor": "Benjam\u00edn Solari Parravicini", "tags": ["De amor", "De sue\u00f1os", "De m\u00fasica", "Mal"]}
{"text": "\u201eNo tiene sentido odiar a quien amas. Amor en realidad\u201c", "autor": "John Lennon", "tags": ["De amor", "Sentido", "Realidad"]}
{"text": "\u201eEn la primera pasi\u00f3n la mujer ama a su amante, en las otras todo lo que ama es al amor.\u201c", "autor": "George G. Byron", "tags": ["De amor", "De mujeres", "Pasi\u00f3n", "Los amantes"]}
{"text": "\u201eDolor moderado indica amor; dolor en exceso, pura necedad.\u201c", "autor": "William Shakespeare", "tags": ["De amor", "De dolor"]}
{"text": "\u201eEl problema no es repetir el ayer como f\u00f3rmula para salvarse. El problema no es jugar a darse. El problema no es de ocasi\u00f3n. El problema, se\u00f1or, sigue siendo sembrar amor\u201c", "autor": "Silvio Rodr\u00edguez", "tags": ["De amor", "Problema"]}
{"text": "\u201eSiento que las personas tender\u00e1n hacia el amor universal y la ayuda mutua, como el fuego que tiende hacia arriba y el agua hacia abajo; ser\u00e1 inevitable en el mundo.\u201c", "autor": "Mozi", "tags": ["De amor", "De mundo", "Agua"]}
{"text": "\u201eEn la universidad, cuando las personas nos pregunten c\u00f3mo nos conocimos, \u00bfC\u00f3mo les responderemos? La historia es: Crecimos juntos. Pero esa era m\u00e1s la historia con Josh. \u00bfNovios de preparatoria? Esa era la historia de Gen y Peter. As\u00ed que la nuestra \u00bfCu\u00e1l era?", "autor": "Jenny Han", "tags": ["De amor", "Historia"]}
{"text": "\u201eTu amor por m\u00ed no vive en el mundo real. S\u00ed, no niego que sea amor. Pero no todos los amores tienen un cauce por el que correr, y este amor no tiene ning\u00fan cauce en absoluto. Debido a lo que yo soy y a lo que viste, represento para ti un terrible objeto de fascinaci\u00f3n. Yo soy una cabeza cortada, como las que usaban las tribus primitivas y los antiguos alquimistas, que las ung\u00edan con aceite y colocaban un pedazo de oro sobre la lengua para hacerlas pronunciar profec\u00edas. Y qui\u00e9n sabe si un largo trato con una cabeza cortada no puede llevar a un extra\u00f1o conocimiento. Por tal conocimiento, ya se habr\u00eda pagado lo suficiente. Pero est\u00e1 muy lejos del amor y muy lejos de la vida corriente. Como personas reales, no existimos el uno para el otro.", "autor": "Iris Murdoch", "tags": ["De amor", "De vida", "De mundo", "De esperanza"]}
{"text": "\u201eMi manera de definir el amor entre dos amigos, el amor entre dos hermanos, el amor entre padres e hijos, el amor en una pareja, el amor:", "autor": "Jorge Bucay", "tags": ["De amor", "De mentira", "Padre", "Hijas"]}
{"text": "\u201eMis padres no compart\u00edan s\u00f3lo un amor peculiar, ellos compart\u00edan una fe en las posibilidades de esta naci\u00f3n. Ellos me dieron un nombre africano, Barack, o bendito, acreditando que en una Am\u00e9rica tolerante el nombre no es ninguna barrera al \u00e9xito. Me imaginaban yendo a las mejores escuelas en la tierra, aunque ellos no fueran ricos, porque en una Am\u00e9rica generosa uno no tiene que ser rico para alcanzar su potencial.\u201c", "autor": "Barack Obama", "tags": ["De amor", "De escuela", "De fe", "Padre"]}
{"text": "\u201eEl peligro del m\u00e1s solitario es el amor, el amor a todo lo que vive.\u201c", "autor": "Friedrich Nietzsche", "tags": ["De amor"]}
{"text": "\u201eLos satanistas con trabajos bien pagados no necesitan entrevistas como esta. Nosotros creemos que ir de fiesta es malo. Es mejor sentarse y cortarse, que salir y divertirse. Algunas veces tienes que plantarle cara a algunos cambios, que deben ser tomados con mano dura. Hace varios a\u00f1os prescind\u00ed de sentir amor.\u201c", "autor": "\u00d8ystein Aarseth", "tags": ["De amor", "Cambio"]}
{"text": "\u201eEl amor es el estado en el cual, la mayor\u00eda de las veces, el hombre ve las cosas como no son.\u201c", "autor": "Friedrich Nietzsche", "tags": ["De amor", "De hombres"]}
{"text": "\u201eEse v\u00ednculo humano esencial entre el mundo y el infinito. El \u00fanico sitio donde el torrente sangu\u00edneo toca la eternidad. Lo que importa es el amor y el deseo. Aqu\u00ed en la oscuridad se puede hacer como en cualquier otra parte. Quiz\u00e1 mejor que en muchas otras\u2026 As\u00ed es volar\u201c", "autor": "Stephen King", "tags": ["De amor", "De mundo"]}
{"text": "\u201e\u00a1Ay, los vicios humanos! Son ellos los que contienen la prueba de nuestro amor por el infinito.\u201c", "autor": "Charles Baudelaire", "tags": ["De amor"]}
{"text": "\u201eCuando uno est\u00e1 enamorado, empieza siempre por enga\u00f1arse a s\u00ed mismo para terminar enga\u00f1ando a los dem\u00e1s. Eso es lo que el mundo llama un amor rom\u00e1ntico.\u201c", "autor": "Oscar Wilde", "tags": ["De amor", "De mundo", "Enga\u00f1ando"]}
{"text": "\u201eEl amor de mi padre fue siempre fuerte, el glamour de mi madre sigue viviendo, sin embargo, por dentro me sent\u00eda sola por razones desconocidas\u2026\u201c", "autor": "Lana del Rey", "tags": ["De amor", "Padre", "Fuerte"]}
{"text": "\u201eNo te amo como si fueras rosa de sal, topacio", "autor": "Pablo Neruda", "tags": ["De amor", "De sue\u00f1os", "Problema", "Alma"]}
{"text": "\u201eAs\u00ed jur\u00f3; pero de veras dicen que aquellos juramentos dados en el amor no alcanzan los o\u00eddos de los dioses.\u201c", "autor": "Cal\u00edmaco de Cirene", "tags": ["De amor", "De Dios"]}
{"text": "\u201eEL AMENAZADO", "autor": "Jorge Luis Borges", "tags": ["De amor", "De muerte", "De mujeres", "De hombres"]}
{"text": "\u201eDESPEDIDA DE UN PAISAJE", "autor": "Wis\u0142awa Szymborska", "tags": ["De amor", "De vida", "De dolor", "De tristeza"]}
{"text": "\u201e\u2026 la mujer invent\u00f3 el amor sin compa\u00f1ero. Aventur\u00e1ndose sola en territorios alucinantes, con la audacia de quien no conoce los riesgos\u201c", "autor": "Isabel Allende", "tags": ["De amor", "De mujeres"]}
{"text": "\u201eNo hagas cualquier cosa s\u00f3lo para ser famoso. Realmente fracasar\u00edas si lo hicieras sin amor y vocaci\u00f3n.\u201c", "autor": "Zac Efron", "tags": ["De amor"]}
{"text": "\u201eAmamos lo que amamos, la raz\u00f3n no entra en juego. En muchos aspectos, el amor m\u00e1s insensato es el amor m\u00e1s verdadero.\u201c", "autor": "Patrick Rothfuss", "tags": ["De amor"]}
{"text": "\u201eNo se mide el amor por el n\u00famero de caricias, sino por la frecuencia con que uno y otro se comprenden.\u201c", "autor": "Herbert Spencer", "tags": ["De amor"]}
{"text": "\u201eEl idioma alem\u00e1n queda bien con el heavy metal. El franc\u00e9s podr\u00eda ser el idioma del amor, pero el alem\u00e1n es el idioma de la furia.\u201c", "autor": "Christian Lorenz", "tags": ["De amor"]}
{"text": "\u201eS\u00f3lo hay una cosa m\u00e1s grande que el amor a la libertad, el odio a quien te la quita.\u201c", "autor": "Ernesto Guevara", "tags": ["De amor", "De odio", "Libertad"]}
{"text": "\u201eEl amigo interesado mira a su amor propio; el verdadero, s\u00f3lo al bien del amigo.\u201c", "autor": "Francisco de Quevedo", "tags": ["De amor", "De verdad"]}
{"text": "\u201eCon todo, no pod\u00eda reprimir los v\u00edvidos recuerdos de aquella pasi\u00f3n, su cuerpo se pon\u00eda tenso y comenzaba a temblar. Por fin la tensi\u00f3n se aflojaba y una deliciosa sensaci\u00f3n de plenitud recorr\u00eda sus miembros. Su amor del pasado hab\u00eda vuelto a la vida.\u201c", "autor": "Yasunari Kawabata", "tags": ["De amor", "De vida", "Sensaci\u00f3n", "Pasado"]}
{"text": "\u201eEl amor nace, vive y muere en los ojos.\u201c", "autor": "William Shakespeare", "tags": ["De amor"]}
{"text": "\u201ePor muy exigente que se sea en amor, se perdonan m\u00e1s faltas que en la amistad\u201c", "autor": "Jean de La Bruyere", "tags": ["De amor", "De amistad", "De gente"]}
{"text": "\u201eEl amor y la amistad se excluyen mutuamente.\u201c", "autor": "Jean de La Bruyere", "tags": ["De amor", "De amistad"]}
{"text": "\u201eEs m\u00e1s f\u00e1cil encontrar un amor apasionado que una amistad perfecta.\u201c", "autor": "Jean de La Bruyere", "tags": ["De amor", "De amistad", "De fe"]}
{"text": "\u201eEl objetivo de su vida, desde su", "autor": "Tennessee Williams", "tags": ["De amor", "De vida", "De mujeres", "De hombres"]}
{"text": "\u201eLa amistad es el amor, pero sin sus alas.\u201c", "autor": "George G. Byron", "tags": ["De amor", "De amistad"]}
{"text": "\u201eSi el amor verdadero es raro, m\u00e1s lo es la verdadera amistad\u201c", "autor": "Albert Einstein", "tags": ["De amor", "De amistad"]}
{"text": "\u201eNo conozco nada m\u00e1s despreciable y pat\u00e9tico que un hombre que dedica todas las horas del d\u00eda a hacer dinero por el amor al dinero.\u201c", "autor": "John Davison Rockefeller", "tags": ["De amor", "De hombres", "De dinero"]}
{"text": "\u201ePara\u00edso de la tierra", "autor": "Jos\u00e9 Zorrilla", "tags": ["De amor", "De salud", "Alegr\u00eda"]}
{"text": "\u201eEn el amor siempre hay algo de locura, mas en la locura siempre hay algo de raz\u00f3n.\u201c", "autor": "Friedrich Nietzsche", "tags": ["De amor", "Locura"]}
{"text": "\u201eS\u00f3lo el amor engendra la maravilla. S\u00f3lo el amor convierte en milagro el barro\u201c", "autor": "Silvio Rodr\u00edguez", "tags": ["De amor"]}
{"text": "\u201eGideon era m\u00edo, completamente m\u00edo. Pero aun as\u00ed, una parte de mi mente estaba asombrada de que pudiera tenerlo as\u00ed, de que estuviera desnudo, en una cama que compart\u00edamos, en un apartamento que compart\u00edamos, de que estuviese dentro de m\u00ed, de una parte de m\u00ed, aceptando cada pedazo de mi amor y pasi\u00f3n y devolvi\u00e9ndome mucho m\u00e1s.\u201c", "autor": "Sylvia Day", "tags": ["De amor", "Pasi\u00f3n"]}
{"text": "\u201eQuiz\u00e1 fuera cierto lo que la reina seelie hab\u00eda dicho: el amor nos hace mentirosos.\u201c", "autor": "Cassandra Clare", "tags": ["De amor"]}
{"text": "\u201eTodo padre/madre que pierde a un hijo encuentra el modo de volver a re\u00edr. El timbre se desvanece. El filo se enfr\u00eda. El dolor disminuye. Cada amor est\u00e1 tallado en la p\u00e9rdida. El m\u00edo lo estaba. El tuyo lo est\u00e1. El de tu tataratataratatara nieto lo estar\u00e1. Pero aprendemos a vivir con ese amor.\u201c", "autor": "Jonathan Safran Foer", "tags": ["De amor", "De dolor", "Padre", "P\u00e9rdida"]}
{"text": "\u201ePor eso juzgo y discierno", "autor": "Miguel de Cervantes", "tags": ["De amor", "Infierno"]}
{"text": "\u201eTres cosas conducen a Dios: la m\u00fasica, el amor y la filosof\u00eda.\u201c", "autor": "Plotino", "tags": ["De amor", "De Dios", "De m\u00fasica"]}
{"text": "\u201eEn el amor no existe el libre albedr\u00edo, nadie puede decidir de qui\u00e9n va a enamorarse.\u201c", "autor": "Alejandro Dolina", "tags": ["De amor", "De libros"]}
{"text": "\u201e[\u2026] sent\u00ed en la garganta el nudo gordiano de todos los amores que pudieron haber sido y no fueron [\u2026]\u201c", "autor": "Gabriel Garc\u00eda M\u00e1rquez", "tags": ["De amor"]}
{"text": "\u201eTodo comienza cuando el objeto de tu adoraci\u00f3n te da una dosis embriagadora y alucin\u00f3gena de algo que jam\u00e1s te hab\u00edas atrevido a admitir que necesitabas \u2014un c\u00f3ctel t\u00f3xico-sentimental, quiz\u00e1, de un amor estrepitoso y un entusiasmo arrebatador\u2014.\u201c", "autor": "Elizabeth Gilbert", "tags": ["De amor"]}
{"text": "\u201eMato de hambre al amor, para que devore lo que encuentre.\u201c", "autor": "Octavio Paz", "tags": ["De amor", "De hambre"]}
{"text": "\u201eEl amor es como una flor\u2026 hasta la m\u00e1s bella se marchita.\u201c", "autor": "Till Lindemann", "tags": ["De amor", "Las flores"]}
{"text": "\u201eEl amor es la \u00fanica fuerza capaz de cambiar el coraz\u00f3n del hombre y de la humanidad entera.\u201c", "autor": "Benedicto XVI", "tags": ["De amor", "De paz", "Coraz\u00f3n"]}
{"text": "\u201eAmor, pens\u00f3, entregado de forma libre, aceptado de forma voluntaria. No hab\u00eda magia m\u00e1s potente.\u201c", "autor": "Nora Roberts", "tags": ["De amor", "De libros"]}
{"text": "\u201eTodo hace el amor con el silencio. Me hab\u00edan prometido un silencio como un fuego, una casa de silencio. De pronto el templo es un circo y la luz un tambor.\u201c", "autor": "Alejandra Pizarnik", "tags": ["De amor", "Silencio"]}
{"text": "\u201eDespu\u00e9s de todo \u00bfpor qu\u00e9 era necesario amar a un ser humano? Nunca duraba mucho. Hab\u00eda demasiadas diferencias entre cada individuo, y lo que empezaba siendo amor acababa siempre en guerra despiadada\u201c", "autor": "Charles Bukowski", "tags": ["De amor", "De guerra"]}
{"text": "\u201eYo fui educado con odio, y odiaba a la humanidad, un d\u00eda me fui con los hippies y tuve un amor y tambi\u00e9n mucho m\u00e1s.\"\u201c", "autor": "Charly Garc\u00eda", "tags": ["De amor", "De odio"]}
{"text": "\u201eNadie muere por falta de sexo. Es por falta de amor por lo que morimos\u201c", "autor": "Margaret Atwood", "tags": ["De amor", "De sexo"]}
{"text": "\u201eYo no s\u00e9 muy bien qu\u00e9 sea amor, pero de lo que s\u00ed estoy convencido es de que es algo muy distinto al sexo y a la reproducci\u00f3n, con los que lo confunde mi vecino. El amor es puro; el sexo entretenido y sano; y la reproducci\u00f3n, criminal.\u201c", "autor": "Fernando Vallejo", "tags": ["De amor", "De sexo"]}
{"text": "\u201eTu seras mi amor inolvidable entre los dos jamas vendr\u00e1 el olvido.\u201c", "autor": "Enrique Bunbury", "tags": ["De amor", "De vida"]}
{"text": "\u201eJes\u00fas es el inventor del amor desinteresado. Vosotros me dir\u00e9is que el amor ya exist\u00eda. \u00a1Es verdad! Tambi\u00e9n las ondas de radio, y la electricidad existen desde siempre, pero si no hab\u00eda alguien que las descubriera, no lo hubi\u00e9ramos sabido. Jes\u00fas ha declarado verdaderamente qu\u00e9 es el amor. Nosotros hacemos chistes sobre las suegras. \u00c9l ense\u00f1\u00f3 el amor incluso por las suegras. \u00a1As\u00ed pod\u00eda hacerles la comida!\u201c", "autor": "Roberto Benigni", "tags": ["De amor", "De verdad", "De comida"]}
{"text": "\u201eEl odio no disminuye con el odio. El odio disminuye con el amor.\u201c", "autor": "Buda Gautama", "tags": ["De amor", "De odio"]}
{"text": "\u201eEn el arte como en el amor la ternura es lo que da la fuerza.\u201c", "autor": "Oscar Wilde", "tags": ["De amor", "De arte"]}
{"text": "\u201eEs casi ley, los amores eternos, son los m\u00e1s breves.\u201c", "autor": "Mario Benedetti", "tags": ["De amor", "De leyes"]}
{"text": "\u201eY el amor fue el origen del mundo,", "autor": "Knut Hamsun", "tags": ["De amor", "De mundo", "Camino", "Las flores"]}
{"text": "\u201eAmor m\u00edo, no te quiero por vos ni por m\u00ed ni por los dos juntos, no te quiero porque la sangre me llame a quererte, te quiero porque no sos m\u00eda, porque est\u00e1s del otro lado, ah\u00ed donde me invit\u00e1s a saltar y no puedo dar el salto, porque en lo m\u00e1s profundo de la posesi\u00f3n no est\u00e1s en m\u00ed, no te alcanzo, no paso de tu cuerpo, de tu risa, hay horas en que me atormenta que me ames (c\u00f3mo te gusta usar el verbo amar, con qu\u00e9 cursiler\u00eda lo vas dejando caer sobre los platos y las s\u00e1banas y los autobuses), me atormenta tu amor que no me sirve de puente porque un puente no se sostiene de un solo lado.\u201c", "autor": "Julio Cort\u00e1zar", "tags": ["De amor", "Risa"]}
{"text": "\u201eDe un individuo se multiplicaron las muchas personas que habitan la superficie de la tierra. E incluso si ese esp\u00edritu intelectual, sembrado en la tierra y tragado en la sombra, no ve la luz y la fuente de su comienzo, sin embargo, usted cre\u00f3 junto con \u00e9l todo a trav\u00e9s de los cuales \u00e9l, despert\u00f3 con asombro ante aquellas cosas con las que entra en contacto. los sentidos, a veces pueden elevar los ojos de su mente hacia usted, el creador de todo, y pueden reunirse con usted en el amor m\u00e1s elevado y, por lo tanto, pueden regresar a su fuente con alegr\u00eda.\u201c", "autor": "Nicol\u00e1s de Cusa", "tags": ["De amor", "Sentido", "Alegr\u00eda"]}
{"text": "\u201e\u00abHoy tengo que conservar el Amor en mi coraz\u00f3n, porque si no, \u00bfc\u00f3mo soportar\u00e9 el d\u00eda?\u00bb.\u201c", "autor": "Oscar Wilde", "tags": ["De amor", "Coraz\u00f3n"]}
{"text": "\u201eAceptamos el amor que creemos merecer.\u201c", "autor": "Stephen Chbosky", "tags": ["De amor"]}
{"text": "\u201eEl amor no tiene edad; siempre est\u00e1 naciendo.\u201c", "autor": "Blaise Pascal", "tags": ["De amor", "De vejez"]}
{"text": "\u201eBuda dijo: \"El odio nunca es vencido por el odio sino por el amor\", y un malentendido no termina nunca gracias una discusi\u00f3n sino gracias al tacto, la diplomacia, la conciliaci\u00f3n, y un sincero deseo de apreciar el punto de vista de los dem\u00e1s.\u201c", "autor": "Dale Carnegie", "tags": ["De amor", "De odio"]}
{"text": "\u201eEs interesante pensar que t\u00fa eres la \u00fanica persona que le completas y despu\u00e9s darte cuenta que hay millones de personas que han sentido lo mismo en su vida. Al final todos nos sentimos atra\u00eddos por el amor y no podemos evitarlo\u201c", "autor": "Taylor Swift", "tags": ["De amor", "De vida", "De arte", "Sentido"]}
{"text": "\u201eCUESTIONARIO PARA REGISTRO (punto 5) \u00a0 01. Seg\u00fan tu experiencia, \u00bfc\u00f3mo presionan las amistades a un hombre o a una mujer para tener sexo? \u00a0 02. Menciona los requisitos para que una mujer sienta un orgasmo. \u00a0 03. \u00bfCu\u00e1les crees que ser\u00edan los requisitos para que un hombre experimente un orgasmo? \u00a0 04. \u00bfC\u00f3mo influye la madurez mental en el trato sexual? \u00a0 05. \u00bfPor qu\u00e9 a veces las personas fingen amor? \u00a0 06. \u00bfQu\u00e9 ventajas y desventajas tiene para una mujer usar ropa y actitudes provocativas? \u00a0 07. \u00bfCu\u00e1l es la mejor forma de salir de la confusi\u00f3n sexual? \u00a0 08. Lee detenidamente los p\u00e1rrafos de este cap\u00edtulo. Escribe los cinco que te hayan parecido m\u00e1s importantes. \u00a0 TAREA (punto 6) \u00a0 01. Trabajo de investigaci\u00f3n: Explica y detalla con la ayuda de diagramas el proceso de gestaci\u00f3n y alumbramiento.\u201c", "autor": "Carlos Cuauht\u00e9moc S\u00e1nchez", "tags": ["De amor", "De mujeres", "De hombres", "De amistad"]}
{"text": "\u201eQuiero que la gente me regale su amor. No me interesan otras cosas. Quiero actuar hasta que no pueda m\u00e1s. Luego descansar\u00e9.\u201c", "autor": "Libertad Lamarque", "tags": ["De amor", "De gente"]}
{"text": "\u201eEl amor no mira con los ojos, sino con el alma.\u201c", "autor": "William Shakespeare", "tags": ["De amor", "Alma"]}
{"text": "\u201eTom\u00e1s no se daba cuenta en aquella ocasi\u00f3n de que las met\u00e1foras son peligrosas. Con las met\u00e1foras no se juega. El amor puede surgir de una sola met\u00e1fora.\u201c", "autor": "Milan Kundera", "tags": ["De amor"]}
{"text": "\u201eEl amor propio es se\u00f1al de una elevada opini\u00f3n de uno mismo. Si un hombre tiene este amor propio, esto demuestra lo que \u00e9l es.\u201c", "autor": "George Gurdjieff", "tags": ["De amor", "De hombres"]}
{"text": "\u201eEn el amor, uno y uno son uno\u00bb.\u201c", "autor": "Jean Paul Sartre", "tags": ["De amor"]}
{"text": "\u201eCada vez que te sientes agradecido est\u00e1s dando amor, y todo lo que das, lo recibes. Sea que le das las gracias a una persona o que te sientes agradecido por un autom\u00f3vil, unas vacaciones, una puesta de sol, un regalo, una casa nueva o una ocasi\u00f3n emocionante, est\u00e1s dando amor por esas cosas y recibir\u00e1s de vuelta m\u00e1s alegr\u00eda, m\u00e1s salud, m\u00e1s dinero, m\u00e1s experiencias fenomenales, m\u00e1s relaciones incre\u00edbles, m\u00e1s oportunidades.\u201c", "autor": "Rhonda Byrne", "tags": ["De amor", "De dinero", "De salud", "Oportunidad"]}
{"text": "\u201eEl sentimiento es deseo y el deseo es amor.\u201c", "autor": "Rhonda Byrne", "tags": ["De amor"]}
{"text": "\u201e\u00abLa combinaci\u00f3n del pensamiento y el amor es lo que crea la irresistible fuerza de la ley de la atracci\u00f3n.\u00bb\u201c", "autor": "Rhonda Byrne", "tags": ["De amor", "De leyes"]}
{"text": "\u201eNo hay escapatoria de la ley del amor. Es el sentimiento el que da vitalidad al pensamiento. El sentimiento es deseo y el deseo es amor. El pensamiento impregnado de amor es invencible.\u00bb\u201c", "autor": "Rhonda Byrne", "tags": ["De amor", "De leyes"]}
{"text": "\u201eLa \u00fanica historia de amor que he tenido fue con la m\u00fasica.\u201c", "autor": "Maurice Ravel", "tags": ["De amor", "De m\u00fasica", "Historia"]}
{"text": "\u201eQui\u00e9n ganar\u00e1 la batalla de este amor desperdiciado, t\u00fa creyendo que me quieres, yo queri\u00e9ndote creer, si yo te quiero aunque te calles y t\u00fa te callas si te quiero\u201c", "autor": "Ricardo Arjona", "tags": ["De amor"]}
{"text": "\u201eA ese hombre le arde en el pecho el fuego sagrado del amor a la libertad.\u201c", "autor": "Francisco de Miranda", "tags": ["De amor", "De hombres", "Libertad"]}
{"text": "\u201eLa mayor declaraci\u00f3n de amor es la que no se hace; el hombre que siente mucho, habla poco.\u201c", "autor": "Plat\u00f3n", "tags": ["De amor", "De hombres"]}
{"text": "\u201eEl amor es una grave enfermedad mental.\u201c", "autor": "Plat\u00f3n", "tags": ["De amor", "De enfermedades"]}
{"text": "\u201eEl amor consiste en sentir que el ser sagrado late dentro del ser querido.\u201c", "autor": "Plat\u00f3n", "tags": ["De amor"]}
{"text": "\u201eMe di cuenta de que junto a \u00e9l, yo era lo m\u00e1s fuerte y lo m\u00e1s d\u00e9bil que pod\u00eda ser. Y pens\u00e9 que eso es el amor: cuando te expones en toda tu vulnerabilidad.\u201c", "autor": "Sophie Jordan", "tags": ["De amor", "Fuerte"]}
{"text": "\u201eMar\u00eda, pues, o sea, el amor de la gloria celestial, con una libra de nardo genuino, o sea, con la fe de los doce ap\u00f3stoles, ungi\u00f3 la cabeza de la divinidad y los pies de la humanidad, reconociendo que Cristo es Dios y Hombre, que naci\u00f3 y sufri\u00f3 la pasi\u00f3n.\u201c", "autor": "Mar\u00eda (madre de Jes\u00fas)", "tags": ["De amor", "De hombres", "De Dios", "De libros"]}
{"text": "\u201eDos cosas, el amor de Dios y del pr\u00f3jimo, hacen perfecto al hombre.\u201c", "autor": "Antonio de Padua", "tags": ["De amor", "De hombres", "De Dios", "De fe"]}
{"text": "\u201eCristo, en efecto, s\u00f3lo por amor llev\u00f3 a la cruz en su cuerpo el peso de nuestros pecados.\u201c", "autor": "Antonio de Padua", "tags": ["De amor", "De fe", "Cristo"]}
{"text": "\u201eAlegr\u00eda y amor son las alas para las grandes promesas.\u201c", "autor": "Johann Wolfgang von Goethe", "tags": ["De amor", "Alegr\u00eda"]}
{"text": "\u201eLa \u00faltima vez que cre\u00ed que una mujer me amaba, perd\u00ed un imperio y acab\u00e9 crucificado mientras ella se re\u00eda de m\u00ed. No seas tonta, Amanda. El amor no existe. Es una ilusi\u00f3n. No me amas; no puedes amarme.\u201c", "autor": "Sherrilyn Kenyon", "tags": ["De amor", "De mujeres"]}
{"text": "\u201eEl amor es un Dios que coopera para garantizar la seguridad de la ciudad.\u201c", "autor": "Zen\u00f3n de Citio", "tags": ["De amor", "De Dios"]}
{"text": "\u201eSi los amantes del vino y del amor van al infierno\u2026 vac\u00edo debe estar el para\u00edso.\u201c", "autor": "Omar Jayam", "tags": ["De amor", "Infierno", "Vino", "Los amantes"]}
{"text": "\u201eAmor, piedad, gratitud a la vida, a los libros y al mundo me galvanizaban el nervio azul del alma.\u201c", "autor": "Roberto Arlt", "tags": ["De amor", "De vida", "De libros", "De mundo"]}
{"text": "\u201eDesde la primera noche de luna, ambos se hicieron trizas los corazones con un amor de principiantes feroces\u201c", "autor": "Gabriel Garc\u00eda M\u00e1rquez", "tags": ["De amor", "Noche", "Coraz\u00f3n"]}
{"text": "\u201eSi ten\u00e9is la dicha de grabar en el coraz\u00f3n de los ni\u00f1os y de los j\u00f3venes el amor y la confianza en la Virgen Mar\u00eda, hab\u00e9is asegurado su salvaci\u00f3n.\u201c", "autor": "Marcelino Champagnat", "tags": ["De amor", "De ni\u00f1os", "Coraz\u00f3n", "Confianza"]}
{"text": "\u201eT\u00fa no amas. Amas en vano, vanamente. Vanidad de enamorada que se vendi\u00f3 a la ausencia. Este amor te devora, t\u00fa misma ya no existes.\u201c", "autor": "Alejandra Pizarnik", "tags": ["De amor"]}
{"text": "\u201eEl amor es una pasi\u00f3n que todos o casi todos veneran pero que pocos, muy pocos viven realmente.\u201c", "autor": "Octavio Paz", "tags": ["De amor", "Pasi\u00f3n"]}
{"text": "\u201eHace calor de Dios, amor.\u201c", "autor": "Miguel \u00e1ngel Asturias", "tags": ["De amor", "De Dios"]}
{"text": "\u201eTan pobre como es la mesa que carece de pan, as\u00ed la vida m\u00e1s ejemplar resulta vac\u00eda si le falta amor.\u201c", "autor": "Antonio de Padua", "tags": ["De amor", "De vida"]}
{"text": "\u201eCreo que lo que me excitaba de tal manera extrema era la idea po\u00e9tica de morir haciendo el amor. Adem\u00e1s, la debilidad aliada a la fiebre me sumerg\u00edan en esa zona sin relaci\u00f3n con lo cotidiano en la que siempre deposit\u00e9 mi \u00fanica esperanza y que hasta esa noche yac\u00eda en un imperio so\u00f1ado de acceso imposible a causa de su irrealidad.\u201c", "autor": "Alejandra Pizarnik", "tags": ["De amor", "De esperanza", "Noche", "Idea"]}
{"text": "\u201emerece un amor menos salvaje y temible e in\u00fatil que el tuyo.\u201c", "autor": "Alejandra Pizarnik", "tags": ["De amor"]}
{"text": "\u201eFiesta de la autodestrucci\u00f3n \u2014imposible, imposible cualquier cosa, todo imposible, imposible el amor, todo imposible\u201c", "autor": "Alejandra Pizarnik", "tags": ["De amor"]}
{"text": "\u201eSe hace lo que se puede", "autor": "@tonypotosino", "tags": ["De amor"]}
{"text": "\u201eVivir la vida, eso no tiene precio. Quien no haya pasado nunca fr\u00edo no apreciar\u00e1 el valor de una hoguera. Quien nunca haya llorado no disfrutar\u00e1 de los momentos de risas. Quien no haya pasado hambre no valorar\u00e1 un plato de estofado caliente. Quien no conozca la muerte no sentir\u00e1 amor por la vida. Esto es lo que Maga me ense\u00f1\u00f3.\u201c", "autor": "Laura Gallego Garc\u00eda", "tags": ["De amor", "De vida", "De muerte", "De hambre"]}
{"text": "\u201eNo hay amor m\u00e1s sincero que el que sentimos hacia la comida.\u201c", "autor": "George Bernard Shaw", "tags": ["De amor", "De comida"]}
{"text": "\u201eLos \u00fanicos seres que son suficientemente evolucionados para transmitir un amor puro son los perros y los ni\u00f1os.\u201c", "autor": "Johnny Depp", "tags": ["De amor", "De ni\u00f1os", "De perros"]}
{"text": "\u201eEl problema del matrimonio es que se acaba todas las noches despu\u00e9s de hacer el amor, y hay que volver a reconstruirlo todas las ma\u00f1anas antes del desayuno.\u201c", "autor": "Gabriel Garc\u00eda M\u00e1rquez", "tags": ["De amor", "De matrimonio", "Problema", "Noche"]}
{"text": "\u201eSi hay basura en el infierno, el amor es el perro que vigila las puertas.\u201c", "autor": "Charles Bukowski", "tags": ["De amor", "De perros", "Infierno"]}
{"text": "\u201e\u00bfY d\u00f3nde dejas el arte? \u2014pregunt\u00f3 ella. \u2014Es una enfermedad. \u2014\u00bfEl amor? \u2014Una ilusi\u00f3n. \u2014\u00bfLa religi\u00f3n? \u2014El suced\u00e1neo elegante de la fe. \u2014Eres un esc\u00e9ptico. \u2014\u00a1Jam\u00e1s! El escepticismo es el comienzo de la fe. \u2014\u00bfQu\u00e9 eres entonces? \u2014Definir es limitar.\u201c", "autor": "Oscar Wilde", "tags": ["De amor", "De enfermedades", "De fe", "De religi\u00f3n"]}
{"text": "\u201eEl amor es la alegr\u00eda del bien, la maravilla de los sabios, el asombro de los dioses.\u201c", "autor": "Plat\u00f3n", "tags": ["De amor", "De Dios", "Alegr\u00eda"]}
{"text": "\u201eEl amor lo complica todo y tambi\u00e9n se abre paso a trav\u00e9s de todo. (Connor)\u201c", "autor": "Nora Roberts", "tags": ["De amor"]}
{"text": "\u201eEl amor y el arte son lo mismo. Chaplin dec\u00eda que toda obra de arte es una carta de amor escrita a alguien [\u2026]\u201c", "autor": "Ernesto Cardenal", "tags": ["De amor", "De arte"]}
{"text": "\u201eSiento que la conozco menos cuanto m\u00e1s la conozco. (Del amor y otros demonios).\u201c", "autor": "Gabriel Garc\u00eda M\u00e1rquez", "tags": ["De amor"]}
{"text": "\u201eUnos construyen sus casas y otros andan por los bosques; porque el destino del hombre es el amor, y cada uno tiene su propia lucha y su propio camino.\u201c", "autor": "Francisco Brines", "tags": ["De amor", "De hombres", "De destino", "Camino"]}
{"text": "\u201eEl matrimonio es la tumba donde enterramos al amor.\u201c", "autor": "Ninon De Lenclos", "tags": ["De amor", "De matrimonio"]}
{"text": "\u201eAs\u00ed me dijo el demonio una vez: \u00abTambi\u00e9n Dios tiene su infierno: es su amor a los hombres.\u00bb\u201c", "autor": "Friedrich Nietzsche", "tags": ["De amor", "De hombres", "De Dios", "Infierno"]}
{"text": "\u201eCada vez que considero que tu amor es tan ingrato, me meto un dedo en el orto y lo dejo estar un rato.\u201c", "autor": "Doctor Tangalanga", "tags": ["De amor"]}
{"text": "\u201eEl hombre sabe que el amor es, pero no lo que es.\u201c", "autor": "Emanuel Swedenborg", "tags": ["De amor", "De hombres"]}
{"text": "\u201eAmor es ver el mundo con los infantiles ojos de la fantas\u00eda e inmediatez\u201c", "autor": "@tonypotosino", "tags": ["De amor", "De mundo"]}
{"text": "\u201eEl amor, como ciego que es, impide a los amantes ver las divertidas tonter\u00edas que cometen.\u201c", "autor": "William Shakespeare", "tags": ["De amor", "Los amantes"]}
{"text": "\u201eSent\u00eda un amor seguro por la humanidad completa, incluso sus enemigos ideol\u00f3gicos, a quienes consideraba errados por ignorancia y no por intr\u00ednseca maldad.\u201c", "autor": "Isabel Allende", "tags": ["De amor"]}
{"text": "\u201ePor m\u00e1s que me caiga en una cloaca, me levanto y huelo a rosas mi amor\u201c", "autor": "Moria Cas\u00e1n", "tags": ["De amor"]}
